/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Fluent Docs",
  "tagline": "Explore Fluent Docs",
  "url": "https://docs.fluent.org",
  "baseUrl": "/docusaurus-template/",
  "onBrokenLinks": "throw",
  "onBrokenAnchors": "warn",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "Fluent",
  "projectName": "Fluent-docs",
  "presets": [
    [
      "classic",
      {
        "docs": {
          "routeBasePath": "/",
          "sidebarPath": "/home/marcuswentz/github/fluent-docusaurus-test/sidebars.js",
          "editUrl": "https://github.com/fluentlabs-xyz/"
        },
        "blog": false,
        "theme": {
          "customCss": "/home/marcuswentz/github/fluent-docusaurus-test/src/css/custom.scss"
        },
        "gtag": {
          "trackingID": "GTM-XXXXXXX",
          "anonymizeIP": true
        }
      }
    ]
  ],
  "themeConfig": {
    "algolia": {
      "appId": "CK38X87BB3",
      "apiKey": "6d53d06cfe9c8cb794826061687d47b5",
      "indexName": "Fluent",
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "imageZoom": {
      "options": {
        "margin": 40,
        "background": "#000",
        "scrollOffset": 60
      }
    },
    "navbar": {
      "title": "",
      "hideOnScroll": true,
      "logo": {
        "alt": "Fluent Docs Logo",
        "src": "/img/fluent_documentation_dark.png",
        "srcDark": "/img/fluent_documentation_light.png"
      },
      "items": [
        {
          "href": "https://chainlist.org/?search=fluent&testnets=true",
          "label": "Connect to Fluent",
          "position": "left"
        },
        {
          "href": "https://faucet.dev.gblend.xyz/",
          "label": "Claim Testnet ETH Faucet",
          "position": "left"
        },
        {
          "href": "https://blockscout.dev.gblend.xyz/",
          "label": "Block Explorer",
          "position": "left"
        },
        {
          "href": "https://www.google.com/",
          "label": "List dApp on Ecosystem Page",
          "position": "left"
        },
        {
          "href": "https://github.com/fluentlabs-xyz/",
          "label": "Report Bugs Here",
          "position": "left"
        },
        {
          "href": "https://github.com/fluentlabs-xyz/",
          "label": "GitHub",
          "position": "right"
        }
      ]
    },
    "footer": {
      "links": [
        {
          "title": "General",
          "items": [
            {
              "label": "Home",
              "to": "https://fluent.xyz"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Discord",
              "to": "https://discord.com/invite/fluentxyz"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "GitHub",
              "to": "https://github.com/fluentlabs-xyz/"
            }
          ]
        }
      ],
      "logo": {
        "alt": "Fluent Logo",
        "src": "img/fluent_logo.png",
        "href": "https://github.com/fluentlabs-xyz/",
        "height": 100,
        "width": 100
      },
      "style": "light"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "solidity",
        "python",
        "rust"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "plugins": [
    "docusaurus-plugin-sass",
    "plugin-image-zoom"
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "future": {
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
